temp.pdf: BackgroundGame.pdf GameObject.pdf GameObject.CollHandler.pdf HUD.pdf Junk.pdf Main.pdf PopUpQuiz.pdf Question.pdf RecycleBin.pdf Sysfile.pdf Sysfile.Size.pdf guides.pdF
	pdftk *pdf cat output temp.pdf
	pdftk guides.pdF temp.pdf cat output final.pdf
	rm temp.pdf
